In [1]:
#creating ndarrays
#The easiest way to create an array is to use the array function.

import numpy as np

data1 = [6,7.5,8,0,1]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
#Nested sequences, like a list of equal-length lists, will be converted into 
#a multidimensional array

data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
#ndim checks for the dimension of array
arr2.ndim

2

In [12]:
#checks shape of array
arr2.shape

(2, 4)

In [15]:
#dtype shows type of array
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [19]:
#zeros and ones are functions that create arrays 
#of 0's and 1's respectively
#with a given length or shape

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
#empty function creates an array without initializing
#its values to any particular value
np.empty((2,3,2))

array([[[1.34055738e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.14587773e-312, 3.29587546e-032]],

       [[1.25897804e-047, 2.81898087e+179],
        [1.10637182e+165, 2.00291508e-076],
        [1.26708932e-071, 8.85066660e+165]]])

In [28]:
#arange is like the built-in range function
#but returns an ndarray instead of a list
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])